### ISSUE TITLE
val_args['scale_factors'] = 1 is wrong

### ISSUE THREAD

**Issue by acgtyrant** [TuSimple/TuSimple-DUC#16]
I find that [the 112nd line in solver.py](https://github.com/TuSimple/TuSimple-DUC/blob/master/train/solver.py#L112) `val_args['scale_factors'] = 1` will cause TypeError:

```
Traceback (most recent call last):                   
  File "./train_model.py", line 16, in <module>      
    train_end2end()                                  
  File "./train_model.py", line 13, in train_end2end 
    model.fit()                                      
  File "/home/acgtyrant/Projects/TuSimple-DUC/train/solver.py", line 235, in fit                          
    num_epoch=self.num_epochs,                       
  File "/home/acgtyrant/Projects/TuSimple-DUC/mxnet/python/mxnet/module/base_module.py", line 528, in fit 
    batch_end_callback=eval_batch_end_callback, epoch=epoch)                                              
  File "/home/acgtyrant/Projects/TuSimple-DUC/mxnet/python/mxnet/module/base_module.py", line 240, in score
    for nbatch, eval_batch in enumerate(eval_data):  
  File "/home/acgtyrant/Projects/TuSimple-DUC/tusimple_duc/core/cityscapes_loader.py", line 133, in next  
    if self._get_next():                             
  File "/home/acgtyrant/Projects/TuSimple-DUC/tusimple_duc/core/cityscapes_loader.py", line 149, in _get_next
    image, label = CityLoader._get_single(self.data[i], self.input_args)                                  
  File "/home/acgtyrant/Projects/TuSimple-DUC/tusimple_duc/core/cityscapes_loader.py", line 163, in _get_single
    return utils.get_single_image_duc(item, input_args)                                                   
  File "/home/acgtyrant/Projects/TuSimple-DUC/tusimple_duc/core/utils.py", line 86, in get_single_image_duc
    scale_factor = random.choice(scale_factors)      
  File "/usr/lib/python2.7/random.py", line 275, in choice                                                
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty                        
TypeError: object of type 'int' has no len()
```

**Comment by GrassSunFlower** [comment]
Thx for the reminder, fixed by #17
